<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<SignAssembly>false</SignAssembly>
		<Company>Perzeus Corporation</Company>
		<Product>Local Finance System</Product>
		<PackageId>Local Finance System</PackageId>
		<Authors>Perzeus Corporation</Authors>
		<Platforms>AnyCPU;x64;x86</Platforms>
		<ApplicationIcon>Resources\accounting.ico</ApplicationIcon>
		<PackageIcon>accounting.ico</PackageIcon>
		<PackageIconUrl />
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<Copyright>Perzeus Corporation</Copyright>
		<StartupObject></StartupObject>
		<DelaySign>false</DelaySign>
		<AssemblyOriginatorKeyFile>Local Finance System Key.pfx</AssemblyOriginatorKeyFile>
		<ApplicationHighDpiMode>DpiUnaware</ApplicationHighDpiMode>
		<Version>1.0.11.5</Version>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="Views\Dashboard\TreasuryDashboard\**" />
		<Compile Remove="Views\Manage\AllotmentReleaseDetails\**" />
		<Compile Remove="Views\Manage\ChartOfAccounts\SubMajorAccountGroup\**" />
		<EmbeddedResource Remove="Views\Dashboard\TreasuryDashboard\**" />
		<EmbeddedResource Remove="Views\Manage\AllotmentReleaseDetails\**" />
		<EmbeddedResource Remove="Views\Manage\ChartOfAccounts\SubMajorAccountGroup\**" />
		<None Remove="Views\Dashboard\TreasuryDashboard\**" />
		<None Remove="Views\Manage\AllotmentReleaseDetails\**" />
		<None Remove="Views\Manage\ChartOfAccounts\SubMajorAccountGroup\**" />
	</ItemGroup>
	<ItemGroup>
		<None Remove="Receipts\AF15.rdlc" />
		<None Remove="Receipts\AF51.rdlc" />
		<None Remove="Receipts\AF52.rdlc" />
		<None Remove="Receipts\AF53.rdlc" />
		<None Remove="Receipts\AF54.rdlc" />
		<None Remove="Receipts\AF56.rdlc" />
		<None Remove="Receipts\AF58.rdlc" />
		<None Remove="Reports\1.rdlc" />
		<None Remove="Reports\abstract-of-general-collection.rdlc" />
		<None Remove="Reports\authority-to-debit-account-disbursements.rdlc" />
		<None Remove="Reports\authority-to-debit-account-disbursements.rdlc~RF1f91e66e.TMP" />
		<None Remove="Reports\cash-disbursement-journal.rdlc" />
		<None Remove="Reports\cash-receipts-journal.rdlc" />
		<None Remove="Reports\cashbook.rdlc" />
		<None Remove="Reports\certificate-of-tax-clearance.rdlc" />
		<None Remove="Reports\CertifiedListRptDelinquences.rdlc" />
		<None Remove="Reports\check-disbursements-journal.rdlc" />
		<None Remove="Reports\check-issued.rdlc" />
		<None Remove="Reports\consolidated-receipts.rdlc" />
		<None Remove="Reports\daily-cash-position-report.rdlc" />
		<None Remove="Reports\general-journal.rdlc" />
		<None Remove="Reports\general-ledger.rdlc" />
		<None Remove="Reports\journal-entry-voucher.rdlc" />
		<None Remove="Reports\Ledgers\summary-subsidiary-ledger.rdlc" />
		<None Remove="Reports\list_of_real-property-tax-delinquencies.rdlc" />
		<None Remove="Reports\Ltoms\ListOfSoldRptAtAuction.rdlc" />
		<None Remove="Reports\Ltoms\ListRptDelinquenciesWithLevy.rdlc" />
		<None Remove="Reports\Ltoms\ltom16NoticeDelinqPymntRpt.rdlc" />
		<None Remove="Reports\Ltoms\Ltom17NoticeRptDelinq.rdlc" />
		<None Remove="Reports\Ltoms\Ltom18NoticeRptDelinq.rdlc" />
		<None Remove="Reports\Ltoms\Ltom19NoticeRptDelinq.rdlc" />
		<None Remove="Reports\Ltoms\Ltom20WarrantOfLevy.rdlc" />
		<None Remove="Reports\Ltoms\Ltom21NoticeOfLevy.rdlc" />
		<None Remove="Reports\Ltoms\Ltom22ReportOfLevy.rdlc" />
		<None Remove="Reports\Ltoms\Ltom23NoticeAuctionSaleDelinqRpt.rdlc" />
		<None Remove="Reports\Ltoms\Ltom24NoticeSale.rdlc" />
		<None Remove="Reports\Ltoms\Ltom25PublicAuctionRegFrm.rdlc" />
		<None Remove="Reports\Ltoms\Ltom26ListOfRegisteredBidders.rdlc" />
		<None Remove="Reports\Ltoms\Ltom27UndertakingAndWaiverOfBidders.rdlc" />
		<None Remove="Reports\Ltoms\Ltom28RulesAndRegulationOfPublicAuction.rdlc" />
		<None Remove="Reports\Ltoms\Ltom29CertificateOfSale.rdlc" />
		<None Remove="Reports\Ltoms\Ltom30DeclarationOfForfeitureOfDelinquentRpt.rdlc" />
		<None Remove="Reports\Ltoms\Ltom31ReportOfSale.rdlc" />
		<None Remove="Reports\Ltoms\Ltom32CertificateOfRedemption.rdlc" />
		<None Remove="Reports\Ltoms\Ltom33CancellationOfWarrantOfLevey.rdlc" />
		<None Remove="Reports\Ltoms\Ltom34FinalDeedOfSale.rdlc" />
		<None Remove="Reports\notice-delinquency-in-the-payment-of-rpt.rdlc" />
		<None Remove="Reports\post-trial-balance.rdlc" />
		<None Remove="Reports\pre-trial-balance.rdlc" />
		<None Remove="Reports\procurements-received-journal.rdlc" />
		<None Remove="Reports\rcd.rdlc" />
		<None Remove="Reports\real-property-tax-due-bill.rdlc" />
		<None Remove="Reports\RealPropertyTaxDuesAndPayments.rdlc" />
		<None Remove="Reports\report_of_general_collection.rdlc" />
		<None Remove="Reports\RptStatementOfAccounts.rdlc" />
		<None Remove="Reports\schedule-of-unreleased-cheques.rdlc" />
		<None Remove="Reports\statement-of-appropriations-allotments-obligations-and-balances.rdlc" />
		<None Remove="Reports\statement-of-changes-in-net-assets-equity.rdlc" />
		<None Remove="Reports\statement-of-financial-performance.rdlc" />
		<None Remove="Reports\statement-of-financial-position-report.rdlc" />
		<None Remove="Reports\statement_of_cash_flows.rdlc" />
		<None Remove="Reports\status-of-appropriations-allotments-and-obligation.rdlc" />
		<None Remove="Reports\subsidiary-ledger.rdlc" />
		<None Remove="Reports\transaction_log.rdlc" />
		<None Remove="Views\Dashboard\Budget\ucBudgetSummary.resx~RF15fbe303.TMP" />
		<None Remove="Views\Transactions\Payments\4ln2x4sd.4uw~" />
	</ItemGroup>
	<ItemGroup>
	  <Content Include="Receipts\AF15.rdlc">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Reports\certificate-of-tax-clearance.rdlc">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Reports\Ltoms\ListOfSoldRptAtAuction.rdlc">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Reports\Ltoms\Ltom23NoticeAuctionSaleDelinqRpt.rdlc">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
	<ItemGroup>
	  <Content Include="Reports\Ltoms\ListRptDelinquenciesWithLevy.rdlc">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Reports\Ltoms\Ltom24NoticeSale.rdlc">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Reports\Ltoms\Ltom26ListOfRegisteredBidders.rdlc">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
	<ItemGroup>
		<Content Include="Receipts\AF51.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Receipts\AF52.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Receipts\AF53.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Receipts\AF56.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Receipts\AF58.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\abstract-of-general-collection.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\cash-disbursement-journal.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\cash-receipts-journal.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\cashbook.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\CertifiedListRptDelinquences.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\check-disbursements-journal.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\check-issued.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\consolidated-receipts.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\daily-cash-position-report.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\general-journal.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\Ledgers\general-ledger.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\journal-entry-voucher.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\Ledgers\summary-subsidiary-ledger.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\ListRptDelinquencies.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\Ltoms\Ltom16NoticeDelinqPymntRpt.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\Ltoms\Ltom17NoticeRptDelinq.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\Ltoms\Ltom18NoticeRptDelinq.rdlc">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\Ltoms\Ltom19NoticeRptDelinq.rdlc">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\Ltoms\Ltom20WarrantOfLevy.rdlc">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\Ltoms\Ltom21NoticeOfLevy.rdlc">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\Ltoms\Ltom22ReportOfLevy.rdlc">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\Ltoms\Ltom25PublicAuctionRegFrm.rdlc">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\Ltoms\Ltom27UndertakingAndWaiverOfBidders.rdlc">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\Ltoms\Ltom28RulesAndRegulationOfPublicAuction.rdlc">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\Ltoms\Ltom29CertificateOfSale.rdlc">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\Ltoms\Ltom30DeclarationOfForfeitureOfDelinquentRpt.rdlc">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\Ltoms\Ltom31ReportOfSale.rdlc">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\Ltoms\Ltom32CertificateOfRedemption.rdlc">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\Ltoms\Ltom34FinalDeedOfSale.rdlc">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\Ltoms\Ltom33CancellationOfWarrantOfLevey.rdlc">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\post-trial-balance.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\pre-trial-balance.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\procurements-received-journal.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\rcd.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\schedule-of-released-cheques.rdlc">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\real-property-tax-due-bill.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\RptStatementOfAccounts.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\RealPropertyTaxDuesAndPayments.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\report_of_general_collection.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\schedule-of-unreleased-cheques.rdlc">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\statement-of-appropriations-allotments-obligations-and-balances.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\statement-of-changes-in-net-assets-equity.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\statement-of-financial-performance.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\statement-of-financial-position-report.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\statement_of_cash_flows.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\status-of-appropriations-allotments-and-obligation.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\Ledgers\subsidiary-ledger.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Reports\Ledgers\transaction_log.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\accounting.ico" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="MySql.Data" Version="9.3.0" />
		<PackageReference Include="ReportViewerCore.WinForms" Version="15.1.26" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\ACC.Data\ACC.Data.csproj" />
		<ProjectReference Include="..\RPT.Data\RPT.Data.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="Reports\authority-to-debit-account-disbursements.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<Compile Update="DataSets\dsTreasury.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>dsTreasury.xsd</DependentUpon>
		</Compile>
		<Compile Update="dsLFS.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>dsLFS.xsd</DependentUpon>
		</Compile>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
		<Compile Update="Properties\Settings.Designer.cs">
			<DesignTimeSharedInput>True</DesignTimeSharedInput>
			<AutoGen>True</AutoGen>
			<DependentUpon>Settings.settings</DependentUpon>
		</Compile>
		<Compile Update="Views\Manage\BudgetAppropriations\frmBudgetAppropriationsAdd.cs" />
		<Compile Update="Views\Manage\BudgetAppropriations\frmBudgetAppropriationsEdit.cs" />
		<Compile Update="Views\Manage\BudgetAppropriations\ucBudgetAppropriations.cs" />
		<Compile Update="Views\Manage\RealProperties\ucRealProperties.cs" />
		<Compile Update="Views\Reports\Ltoms\frmLtom22.cs">
		  <SubType>Form</SubType>
		</Compile>
		<Compile Update="Views\Reports\Ltoms\frmLtom21.cs">
		  <SubType>Form</SubType>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
		<None Update="DataSets\dsTreasury.xsd">
			<Generator>MSDataSetGenerator</Generator>
			<LastGenOutput>dsTreasury.Designer.cs</LastGenOutput>
		</None>
		<None Update="dsLFS.xsd">
			<Generator>MSDataSetGenerator</Generator>
			<LastGenOutput>dsLFS.Designer.cs</LastGenOutput>
		</None>
		<None Update="Properties\Settings.settings">
			<Generator>SettingsSingleFileGenerator</Generator>
			<LastGenOutput>Settings.Designer.cs</LastGenOutput>
		</None>
		<None Update="Reports\payment-collection.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<Content Include="Receipts\AF54.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
</Project>