<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RPT.Domain\PropertyAssessment.Domain.csproj" />
    <ProjectReference Include="..\OmniGov.Core\OmniGov.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>
</Project>