<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RPT.Domain\RPT.Domain.csproj" />
  </ItemGroup>
</Project>