<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ACC.Data\ACC.Data.csproj" />
    <ProjectReference Include="..\ACC.Domain\ACC.Domain.csproj" />
    <ProjectReference Include="..\RPT.Domain\RPT.Domain.csproj" />
  </ItemGroup>
</Project>