<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\Manage\ChartOfAccounts\SubMajorAccountGroup\**" />
    <EmbeddedResource Remove="Views\Manage\ChartOfAccounts\SubMajorAccountGroup\**" />
    <None Remove="Views\Manage\ChartOfAccounts\SubMajorAccountGroup\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Reports\authority-to-debit-account-disbursements.rdlc~RF1f91e66e.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="ReportViewerCore.WinForms" Version="15.1.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ACC.Data\ACC.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="dsLFS.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>dsLFS.xsd</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Views\Manage\BudgetAppropriations\frmBudgetAppropriationsAdd.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views\Manage\BudgetAppropriations\frmBudgetAppropriationsEdit.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views\Manage\BudgetAppropriations\ucBudgetAppropriations.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="dsLFS.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>dsLFS.Designer.cs</LastGenOutput>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="Reports\authority-to-debit-account-disbursements.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Reports\cash-disbursement-journal.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Reports\cash-receipts-journal.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Reports\check-disbursements-journal.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Reports\check-issued.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Reports\general-journal.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Reports\general-ledger.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Reports\payment-collection.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Reports\procurements-received-journal.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Reports\status-of-appropriations-allotments-and-obligation.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>