<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Factory.cs~RF4e36f3f.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="MySql.Data" Version="8.0.27" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ACC.Domain\ACC.Domain.csproj" />
  </ItemGroup>

</Project>
