<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Factory.cs~RF4e36f3f.TMP" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="8.0.33" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ACC.Domain\ACC.Domain.csproj" />
  </ItemGroup>
</Project>